### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by serhatgksu** [sweetsoftware/Ares#12]
I get the error message when I start the server.py files. can you help me? 
  File ".\server.py", line 245
    print "Unexpected file: %s" % src

**Comment by sweetsoftware** [comment]
Are you getting this straight after starting the server ?

**Comment by Zormion** [comment]
I had the same problem, relaunch the program with python 2.7 and not 3 because in 3 you need to have brackets with print and the codes written for 2.7 where you don't need them
