### ISSUE TITLE
Error running agent

### ISSUE THREAD

**Issue by domfgbrown** [sweetsoftware/Ares#24]
when I try and run the agent it says "This app cant run on your pc" :/

**Comment by rockeek** [comment]
Change your PC ;-)

**Comment by JavaRockstar** [comment]
Same I'm having no problems running the Server on my Kali Linux machine I can see the HTTP Bot net page fine the problem I'm having is when I create the payload in Linux it gives of errors when executing in Windows. I will next try and create the agent with a Windows host has anyone had a similar problem when building the payloads.

"This app cant run on your pc" I thought this may of been a signing fault I'll post if i find a fix in time id also love to see payload agents for mobile devices too.
