### ISSUE TITLE
Linux Support for DDoS, Keylogging

### ISSUE THREAD

**Issue by kmanwar89** [sweetsoftware/Ares#28]
Hey there,

Loving the software, but it'd be great if there were better support for Linux.  Currently, the screenshot option throws an error on Linux, since the PIL library is only meant for OS X & Windows, same with the DDoS module (requiring the PythonCOM library).

It makes sense to support Linux since so many potential "victim" devices run a Linux kernel, as are academic environments such as my cybersecurity class' environment.

Any support with this would be amazing.

**Comment by sweetsoftware** [comment]
Hi,

The new version has full support for Linux ;)
