### ISSUE TITLE
Document additional functionality clearly

### ISSUE THREAD

**Issue by kmanwar89** [sweetsoftware/Ares#29]
Currently, the keylogging, screenshot, download & upload functions, as well as the DDoS capabilities are not documented anywhere, and are only found by digging through the source code.  I will submit a pull request when I can, but in the meantime it'd be great to fully document all the features of this awesome project.

Thanks for your work on this.

**Comment by sweetsoftware** [comment]
Hello kmanwar89,

Now every functionality is documented in README.md
