### ISSUE TITLE
Error running server.py 

### ISSUE THREAD

**Issue by traget** [sweetsoftware/Ares#30]
/Ares/server# python server.py
Traceback (most recent call last):
  File "server.py", line 282, in <module>
    main()
  File "server.py", line 269, in main
    cherrypy.config.update("conf/server.conf")
  File "/usr/lib/python2.7/dist-packages/cherrypy/config.py", line 81, in update
    for section, valueMap in updateMap.iteritems():
AttributeError: 'str' object has no attribute 'iteritems'

**Comment by Night46** [comment]
assuming you run 'python-cherrypy', try installing 'python-cherrypy3' and it should resolve this error when you run server.py

**Comment by traget** [comment]
I already fixed this Night46 but.. Thanks Anyway!



Sorry for forgeting to close.
