### ISSUE TITLE
Agent.py

### ISSUE THREAD

**Issue by AndrHacK** [sweetsoftware/Ares#33]
Server.py and agent.py erorr

**Comment by JavaRockstar** [comment]
I'm having no problems running the Server on my Kali Linux machine I can see the HTTP Bot net page fine the problem I'm having is when I create the payload in Linux it gives of errors when executing in Windows. I will next try and create the agent with a Windows host has anyone had a similar problem when building the payloads.

**Comment by simantmohan** [comment]
I get the following error while I try to run the agent.py in Windows environment. 
 File "agent.py", line 63
    print command
                ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by sagar03d** [comment]
Which version of python you are using?

**Comment by simantmohan** [comment]
i am using python 3

**Comment by simantmohan** [comment]
I have installed the Server on VPS. it works fine. No problem. I am trying to run the agent.py on my windows machine....

**Comment by sagar03d** [comment]
In python 3, you can only print as:

print("STRING")
But in python 2, the parentheses are not necessary.
You can try with python 2

**Comment by simantmohan** [comment]
I have tried to compile it in kali linux with pythin 2.7 this is the error i get. I guess it is meant to be complied in Windows Environment only.

File "agent.py", line 16, in <module>
    from modules import screenshot
  File "/root/Desktop/Ares/agent/python/modules/screenshot.py", line 1, in <module>
    from PIL import ImageGrab
  File "/usr/lib/python2.7/dist-packages/PIL/ImageGrab.py", line 22, in <module>
    raise ImportError("ImageGrab is macOS and Windows only")
ImportError: ImageGrab is macOS and Windows only

**Comment by simantmohan** [comment]
even I installed python 2.7 in windows. i get following error

Traceback (most recent call last):
  File "agent.py", line 3, in <module>
    import requests
ImportError: No module named requests

**Comment by simantmohan** [comment]
Hi Thanks For your help, I had to install dependencies. Also, PIL was creating a problem so I installed Pillow and it got resolved. Yet there is an issue. I have posted it separately.

**Comment by kimocoder** [comment]
python-requests is missing. missing dependencies. 

have pip? then install using "pip install requests"
