### ISSUE TITLE
 Can I use agent on Linux? How to generate？

### ISSUE THREAD

**Issue by crazyHH** [sweetsoftware/Ares#34]
I want linux machine on the line, how to do ？Use python agent.py install order, but I tried not。

**Comment by Xyntax** [comment]
Goto agent/python/agent.py line 16 
comment this line with '#'
```
# from modules import screenshot
```
Then start the agent session with Python
`cd agent/python`
`python agent.py`

**Comment by sweetsoftware** [comment]
Linux agent now supports screenshots.
