### ISSUE TITLE
python ./ares.py (server dir)

### ISSUE THREAD

**Issue by Ethhunt** [sweetsoftware/Ares#43]
Good Evening,

Trying to follow the instruction and run ./ares.py (server dir) i get the following error;

Traceback  (most recent call last);
    File "ares.py", line 15, in <module>
      from models import_db
      File /home/_____/Tools/Ares/server/model.py". line 5, in <modules>
      from flask_sqlalchemy import SQLAlchemy

ImportError: No module named flask_sqlalchemy 

I tried to go in and install flask the latest version. I tried to review line (5) by opening the .py file in leafpad. I didnt see anything that was off. Any assistance would greatly be appreciated!!

**Comment by sweetsoftware** [comment]
Hi,

Did you install the requirements (pip install -r requirements.txt) ?

**Comment by Ethhunt** [comment]
Yes,

But I got the following error; "could not find a version that statisfies the requirement dist3==0.1.1 (from -r requirements.txt (line 5)) (from versions: 0.1.2) No matching distribution found for dis3==0.1.1 (from -r -requirements.txt line 5)

Any idea? I thought it wasnt installing because im not logged in as root so I 'sudo' - pip install -r requirements and still got that error.

**Comment by sweetsoftware** [comment]
Hello, you are using Python 3. Please use Python 2 instead:

`pip2 install - r requirements.txt`

**Comment by whit3he4d** [comment]
there is no version 0.1.1 ... changed the requ. and it worked.
But not built agent yet.

**Comment by sweetsoftware** [comment]
You are right, there is a bug indeed. I removed this requirement, which is not necessary.
Tested agent building and server, which seems to work. Kindly check it works for you too.
