### ISSUE TITLE
Making the server stay up

### ISSUE THREAD

**Issue by silianrail** [sweetsoftware/Ares#44]
Everything works. Your software is awesome to play with. =)

But I was wondering how to get the server to stay active after I exit my terminal session from ssh.
Similar to how starting up an Apache server will stay active unless the service is stopped.

Sorry, I'm not very familiar with running Python servers.

**Comment by sweetsoftware** [comment]
Hello,

Thanks. You can run the server as a systemd service (https://patrakov.blogspot.fr/2011/01/writing-systemd-service-files.html) or you can use screen/tmux etc ...

**Comment by silianrail** [comment]
sikk. thanks for clarifying.
