### ISSUE TITLE
I miss an password for the webinterface

### ISSUE THREAD

**Issue by MarcellxD** [sweetsoftware/Ares#7]
An login for the web/botinterface because if ist online and any body finds your ip than he has the full control

**Comment by sweetsoftware** [comment]
Hi,

Well, there is no built in authentication, but it doesn't mean you have to leave it open. What you can do is configure the application behind a reverse proxy server (e.g Apache) and setup HTTP Authentication.

**Comment by heticor915** [comment]
But I think that this is an important point, we need to add an official authentication method.

**Comment by sweetsoftware** [comment]
Hi,

Built-in authentication is now available. Feel free to report any bugs or unintended behaviour.

**Comment by MarcellxD** [comment]
Thank you very much 01:02, 11. April 2016, Kevin LOCATI <notifications@github.com>:Hi, Built-in authentication is now available. Feel free to report any bugs or unintended behaviour. —You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub     -- Sent from Yandex.Mail for mobile
